window.OCTO_DATA = {
  "meta": {
    "version": "1.18.0",
    "points": 51,
    "iconBase": "https://octowow.st/talents/icons/"
  },
  "classes": {
    "warrior": {
      "name": "Warrior",
      "spec": "Protection",
      "trees": [
        "Arms",
        "Fury",
        "Protection"
      ],
      "max": [
        49,
        55,
        53
      ],
      "icon": "class_warrior",
      "stats": [
        "Stamina",
        "Defense",
        "Armor",
        "Block Value / Block Chance",
        "Hit",
        "Strength / Attack Power",
        "Agility / Crit"
      ],
      "role": "dungeon tank"
    },
    "warlock": {
      "name": "Warlock",
      "spec": "Affliction",
      "trees": [
        "Affliction",
        "Demonology",
        "Destruction"
      ],
      "max": [
        47,
        48,
        51
      ],
      "icon": "class_warlock",
      "stats": [
        "Spell Hit",
        "Shadow Spell Power",
        "Intellect",
        "Stamina",
        "Spell Crit",
        "Spirit"
      ],
      "role": "dungeon DPS"
    },
    "priest": {
      "name": "Priest",
      "spec": "Discipline",
      "trees": [
        "Discipline",
        "Holy",
        "Shadow"
      ],
      "max": [
        49,
        47,
        50
      ],
      "icon": "class_priest",
      "stats": [
        "Healing Power",
        "Intellect",
        "Spirit",
        "MP5",
        "Stamina",
        "Spell Crit"
      ],
      "role": "dungeon healer"
    }
  },
  "talents": {
    "warrior": [
      {
        "tree": "Arms",
        "slot": 0,
        "name": "Improved Heroic Strike",
        "icon": "ability_rogue_ambush",
        "ranks": 3,
        "desc": "Snižuje cenu Heroic Strike o [1/2/3] rage.",
        "requires": null,
        "id": "warrior_arms_improved_heroic_strike"
      },
      {
        "tree": "Arms",
        "slot": 1,
        "name": "Tactical Mastery",
        "icon": "spell_nature_enchantarmor",
        "ranks": 5,
        "desc": "Při změně stance si ponecháš až [5/10/15/20/25] rage.",
        "requires": null,
        "id": "warrior_arms_tactical_mastery"
      },
      {
        "tree": "Arms",
        "slot": 2,
        "name": "Improved Rend",
        "icon": "ability_gouge",
        "ranks": 2,
        "desc": "Zvyšuje bleed damage schopnosti Rend o [10/20] %.",
        "requires": null,
        "id": "warrior_arms_improved_rend"
      },
      {
        "tree": "Arms",
        "slot": 4,
        "name": "Improved Charge",
        "icon": "ability_warrior_charge",
        "ranks": 2,
        "desc": "Charge generuje o [5/10] rage více.",
        "requires": null,
        "id": "warrior_arms_improved_charge"
      },
      {
        "tree": "Arms",
        "slot": 5,
        "name": "Deflection",
        "icon": "ability_parry",
        "ranks": 5,
        "desc": "Zvyšuje šanci na parry o [1/2/3/4/5] %.",
        "requires": null,
        "id": "warrior_arms_deflection"
      },
      {
        "tree": "Arms",
        "slot": 6,
        "name": "Improved Thunder Clap",
        "icon": "ability_thunderclap",
        "ranks": 3,
        "desc": "Snižuje cenu Thunder Clap o [1/2/4] rage a zvyšuje jeho damage o [20/40/60] %.",
        "requires": null,
        "id": "warrior_arms_improved_thunder_clap"
      },
      {
        "tree": "Arms",
        "slot": 8,
        "name": "Master Strike",
        "icon": "master_strike_1",
        "ranks": 1,
        "desc": "Útok za 35 % weapon damage s efektem podle hlavní zbraně: mace dezorientuje, sword odzbrojí, axe znehybní, polearm sesadí mountnutý cíl a přidá damage, fist srazí k zemi, staff zvýší parry, dagger umlčí.",
        "requires": null,
        "id": "warrior_arms_master_strike"
      },
      {
        "tree": "Arms",
        "slot": 9,
        "name": "Improved Overpower",
        "icon": "inv_sword_05",
        "ranks": 2,
        "desc": "Zvyšuje critical strike chance Overpower o [25/50] %.",
        "requires": null,
        "id": "warrior_arms_improved_overpower"
      },
      {
        "tree": "Arms",
        "slot": 10,
        "name": "Deep Wounds",
        "icon": "ability_backstab",
        "ranks": 3,
        "desc": "Critical strike způsobí bleed za [20/40/60] % průměrného melee weapon damage během 6 sec.",
        "requires": null,
        "id": "warrior_arms_deep_wounds"
      },
      {
        "tree": "Arms",
        "slot": 12,
        "name": "Two-Handed Weapon Specialization",
        "icon": "inv_axe_09",
        "ranks": 3,
        "desc": "Zvyšuje damage s two-handed melee zbraněmi o [2/4/6] % a skill se všemi two-handed zbraněmi o [1/2/3].",
        "requires": null,
        "id": "warrior_arms_two_handed_weapon_specialization"
      },
      {
        "tree": "Arms",
        "slot": 13,
        "name": "Impale",
        "icon": "ability_searingarrow",
        "ranks": 2,
        "desc": "Zvyšuje bonus critical damage tvých schopností v Battle, Defensive a Berserker Stance o [10/20] %.",
        "requires": "warrior_arms_deep_wounds",
        "id": "warrior_arms_impale"
      },
      {
        "tree": "Arms",
        "slot": 14,
        "name": "Master of Arms",
        "icon": "garrison_weaponupgrade",
        "ranks": 5,
        "desc": "Přidává efekty podle typu zbraně: Axe crit +[1/2/3/4/5] %, Mace ignoruje [1.2/2.4/3.6/4.8/6] armor za level cíle, Sword má [1/2/3/4/5] % šanci na extra attack, Polearm zvyšuje melee range o [0.4/0.8/1.2/1.6/2.0] yd.",
        "requires": null,
        "id": "warrior_arms_master_of_arms"
      },
      {
        "tree": "Arms",
        "slot": 17,
        "name": "Sweeping Strikes",
        "icon": "ability_rogue_slicedice",
        "ranks": 1,
        "desc": "Dalších 5 schopností a main-hand melee útoků zasáhne i dalšího blízkého protivníka.",
        "requires": null,
        "id": "warrior_arms_sweeping_strikes"
      },
      {
        "tree": "Arms",
        "slot": 18,
        "name": "Precision Cut",
        "icon": "ability_hunter_swiftstrike",
        "ranks": 3,
        "desc": "Zvyšuje base damage Execute o [15/30/45] %.",
        "requires": null,
        "id": "warrior_arms_precision_cut"
      },
      {
        "tree": "Arms",
        "slot": 20,
        "name": "Improved Disciplines",
        "icon": "ability_warrior_improveddisciplines",
        "ranks": 3,
        "desc": "Snižuje cooldown Retaliation, Recklessness a Shield Wall o [4/8/12] min.",
        "requires": null,
        "id": "warrior_arms_improved_disciplines"
      },
      {
        "tree": "Arms",
        "slot": 21,
        "name": "Improved Slam",
        "icon": "ability_warrior_decisivestrike",
        "ranks": 2,
        "desc": "Snižuje cast time i global cooldown Slam o [0.3/0.5] sec.",
        "requires": null,
        "id": "warrior_arms_improved_slam"
      },
      {
        "tree": "Arms",
        "slot": 22,
        "name": "Boundless Anger",
        "icon": "ability_warrior_strengthofarms",
        "ranks": 3,
        "desc": "Zvyšuje maximální Rage o [10/20/30].",
        "requires": null,
        "id": "warrior_arms_boundless_anger"
      },
      {
        "tree": "Arms",
        "slot": 25,
        "name": "Mortal Strike",
        "icon": "ability_warrior_savageblow",
        "ranks": 1,
        "desc": "Útok za 115 % weapon damage, který zraní cíl a na 10 sec sníží účinnost jeho přijímaného léčení o 50 %.",
        "requires": null,
        "id": "warrior_arms_mortal_strike"
      },
      {
        "tree": "Fury",
        "slot": 0,
        "name": "Booming Voice",
        "icon": "spell_nature_purge",
        "ranks": 5,
        "desc": "Zvyšuje area of effect všech shoutů o [12/24/36/48/60] % a trvání Battle Shout a Demoralizing Shout o [12/24/36/48/60] %.",
        "requires": null,
        "id": "warrior_fury_booming_voice"
      },
      {
        "tree": "Fury",
        "slot": 1,
        "name": "Cruelty",
        "icon": "ability_rogue_eviscerate",
        "ranks": 5,
        "desc": "Zvyšuje melee critical strike chance o [1/2/3/4/5] %.",
        "requires": null,
        "id": "warrior_fury_cruelty"
      },
      {
        "tree": "Fury",
        "slot": 2,
        "name": "Dual Wield Specialization",
        "icon": "ability_dualwield",
        "ranks": 5,
        "desc": "Zvyšuje damage offhand zbraně o [5/10/15/20/25] % a hit chance offhand zbraně o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warrior_fury_dual_wield_specialization"
      },
      {
        "tree": "Fury",
        "slot": 4,
        "name": "Unbridled Wrath",
        "icon": "spell_nature_stoneclawtotem",
        "ranks": 5,
        "desc": "Melee zásah zbraní má [15/30/45/60/75] % šanci vygenerovat 1 rage navíc. Efekt je dvojnásobný pro two-handed zbraně.",
        "requires": null,
        "id": "warrior_fury_unbridled_wrath"
      },
      {
        "tree": "Fury",
        "slot": 5,
        "name": "Improved Shouts",
        "icon": "ability_warrior_commandingshout",
        "ranks": 5,
        "desc": "Zvyšuje attack power bonus Battle Shout o [5/10/15/20/25] % a attack power redukci Demoralizing Shout o [8/16/24/32/40] %.",
        "requires": null,
        "id": "warrior_fury_improved_shouts"
      },
      {
        "tree": "Fury",
        "slot": 6,
        "name": "Piercing Howl",
        "icon": "spell_shadow_deathscream",
        "ranks": 1,
        "desc": "Zpomalí všechny nepřátele poblíž warriora o 50 % na 6 sec.",
        "requires": null,
        "id": "warrior_fury_piercing_howl"
      },
      {
        "tree": "Fury",
        "slot": 8,
        "name": "Blood Craze",
        "icon": "spell_shadow_summonimp",
        "ranks": 3,
        "desc": "Po obdržení critical hitu regeneruješ [2/4/6] % celkového zdraví během 6 sec.",
        "requires": null,
        "id": "warrior_fury_blood_craze"
      },
      {
        "tree": "Fury",
        "slot": 9,
        "name": "Battlefield Mobility",
        "icon": "ability_rogue_sprint",
        "ranks": 2,
        "desc": "Snižuje cooldown Intercept a Intervene o [5/10] sec a Charge o [2/4] sec.",
        "requires": null,
        "id": "warrior_fury_battlefield_mobility"
      },
      {
        "tree": "Fury",
        "slot": 10,
        "name": "Enrage",
        "icon": "spell_shadow_unholyfrenzy",
        "ranks": 5,
        "desc": "Po obdržení critical hitu získáš na 8 sec melee damage bonus [4/8/12/16/20] %.",
        "requires": null,
        "id": "warrior_fury_enrage"
      },
      {
        "tree": "Fury",
        "slot": 12,
        "name": "Improved Pummel",
        "icon": "inv_gauntlets_04",
        "ranks": 2,
        "desc": "Pummel má [50/100] % šanci zpomalit cíl na 4 sec a prodlužuje lockout školy kouzel o [1/2] sec.",
        "requires": null,
        "id": "warrior_fury_improved_pummel"
      },
      {
        "tree": "Fury",
        "slot": 13,
        "name": "Improved Whirlwind",
        "icon": "ability_whirlwind",
        "ranks": 3,
        "desc": "Snižuje cooldown Whirlwind o [1/1/2] sec.",
        "requires": null,
        "id": "warrior_fury_improved_whirlwind"
      },
      {
        "tree": "Fury",
        "slot": 14,
        "name": "Death Wish",
        "icon": "spell_shadow_deathpact",
        "ranks": 1,
        "desc": "Aktivace zvýší fyzický damage o 20 % a dá imunitu na Fear, ale sníží armor a všechny resistance o 20 %. Trvá 30 sec.",
        "requires": null,
        "id": "warrior_fury_death_wish"
      },
      {
        "tree": "Fury",
        "slot": 16,
        "name": "Improved Execute",
        "icon": "inv_sword_48",
        "ranks": 2,
        "desc": "Snižuje rage cenu Execute o [2/5].",
        "requires": null,
        "id": "warrior_fury_improved_execute"
      },
      {
        "tree": "Fury",
        "slot": 17,
        "name": "Improved Berserker Rage",
        "icon": "spell_nature_ancestralguardian",
        "ranks": 2,
        "desc": "Berserker Rage vygeneruje [5/10] Rage a má [50/100] % šanci odstranit movement impairing efekty při aktivaci.",
        "requires": null,
        "id": "warrior_fury_improved_berserker_rage"
      },
      {
        "tree": "Fury",
        "slot": 18,
        "name": "Flurry",
        "icon": "ability_ghoulfrenzy",
        "ranks": 5,
        "desc": "Po melee critu zvýší attack speed dalších 3 swingů o [10/15/20/25/30] %.",
        "requires": null,
        "id": "warrior_fury_flurry"
      },
      {
        "tree": "Fury",
        "slot": 21,
        "name": "Blood Drinker",
        "icon": "racial_troll_berserk",
        "ranks": 3,
        "desc": "Během Enrage, Death Wish nebo Recklessness ti melee útoky a ability obnovují [1/1/2] % maximálního zdraví.",
        "requires": null,
        "id": "warrior_fury_blood_drinker"
      },
      {
        "tree": "Fury",
        "slot": 25,
        "name": "Bloodthirst",
        "icon": "spell_nature_bloodlust",
        "ranks": 1,
        "desc": "Okamžitý útok za 100 damage + 35 % Attack Power a na 6 sec zvýší movement speed o 10 %.",
        "requires": null,
        "id": "warrior_fury_bloodthirst"
      },
      {
        "tree": "Protection",
        "slot": 0,
        "name": "Improved Bloodrage",
        "icon": "ability_racial_bloodrage",
        "ranks": 2,
        "desc": "Zvyšuje instant Rage z Bloodrage o [2/5].",
        "requires": null,
        "id": "warrior_protection_improved_bloodrage"
      },
      {
        "tree": "Protection",
        "slot": 1,
        "name": "Shield Specialization",
        "icon": "inv_shield_06",
        "ranks": 5,
        "desc": "Zvyšuje block chance se štítem o [1/2/3/4/5] % a při blocku generuje [1/2/3/4/5] rage.",
        "requires": null,
        "id": "warrior_protection_shield_specialization"
      },
      {
        "tree": "Protection",
        "slot": 2,
        "name": "Anticipation",
        "icon": "spell_nature_mirrorimage",
        "ranks": 3,
        "desc": "Zvyšuje Defense skill o [7/14/20].",
        "requires": null,
        "id": "warrior_protection_anticipation"
      },
      {
        "tree": "Protection",
        "slot": 4,
        "name": "Iron Will",
        "icon": "spell_magic_magearmor",
        "ranks": 5,
        "desc": "Zvyšuje šanci odolat Stun a Charm efektům o [3/6/9/12/15] %.",
        "requires": null,
        "id": "warrior_protection_iron_will"
      },
      {
        "tree": "Protection",
        "slot": 5,
        "name": "Toughness",
        "icon": "spell_holy_devotion",
        "ranks": 5,
        "desc": "Zvyšuje armor z itemů o [2/4/6/8/10] % a damage absorbovaný štítem o [3/6/9/12/15] %.",
        "requires": null,
        "id": "warrior_protection_toughness"
      },
      {
        "tree": "Protection",
        "slot": 6,
        "name": "Last Stand",
        "icon": "spell_holy_ashestoashes",
        "ranks": 1,
        "desc": "Aktivace dočasně zvýší maximum zdraví o 30 % na 20 sec. Po skončení efektu se přidané životy ztratí.",
        "requires": null,
        "id": "warrior_protection_last_stand"
      },
      {
        "tree": "Protection",
        "slot": 8,
        "name": "Improved Intervene",
        "icon": "ability_warrior_intervene",
        "ranks": 2,
        "desc": "Po použití Intervene máš [50/100] % šanci získat na 3 sec imunitu proti movement impairing efektům.",
        "requires": null,
        "id": "warrior_protection_improved_intervene"
      },
      {
        "tree": "Protection",
        "slot": 9,
        "name": "Improved Taunt",
        "icon": "spell_nature_reincarnation",
        "ranks": 2,
        "desc": "Snižuje cooldown Taunt o [1/2] sec.",
        "requires": null,
        "id": "warrior_protection_improved_taunt"
      },
      {
        "tree": "Protection",
        "slot": 10,
        "name": "Improved Revenge",
        "icon": "ability_warrior_revenge",
        "ranks": 3,
        "desc": "Revenge má [15/30/45] % šanci stunout cíl na 3 sec a jeho cooldown je snížen o [0.5/1/1.5] sec.",
        "requires": null,
        "id": "warrior_protection_improved_revenge"
      },
      {
        "tree": "Protection",
        "slot": 12,
        "name": "Gag Order",
        "icon": "ability_warrior_shieldbash",
        "ranks": 2,
        "desc": "Shield Slam má dodatečnou [50/100] % šanci dispellnout 1 magic efekt z cíle a Shield Bash má [50/100] % šanci umlčet cíl na 3 sec.",
        "requires": null,
        "id": "warrior_protection_gag_order"
      },
      {
        "tree": "Protection",
        "slot": 13,
        "name": "Improved Disarm",
        "icon": "ability_warrior_disarm",
        "ranks": 2,
        "desc": "Snižuje cooldown Disarm o [10/20] sec.",
        "requires": null,
        "id": "warrior_protection_improved_disarm"
      },
      {
        "tree": "Protection",
        "slot": 16,
        "name": "Defiance",
        "icon": "ability_warrior_innerrage",
        "ranks": 5,
        "desc": "Zvyšuje threat generovaný v Defensive Stance o dalších [3/6/9/12/15] %.",
        "requires": null,
        "id": "warrior_protection_defiance"
      },
      {
        "tree": "Protection",
        "slot": 17,
        "name": "One-Handed Weapon Specialization",
        "icon": "inv_sword_20",
        "ranks": 5,
        "desc": "Zvyšuje damage s one-handed melee zbraněmi o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warrior_protection_one_handed_weapon_specialization"
      },
      {
        "tree": "Protection",
        "slot": 18,
        "name": "Shield Slam",
        "icon": "inv_shield_05",
        "ranks": 1,
        "desc": "Úder štítem způsobí 174–184 damage upravený podle shield block value a attack power. Generuje vysoký threat a má 50 % šanci dispellnout 1 magic efekt z cíle.",
        "requires": null,
        "id": "warrior_protection_shield_slam"
      },
      {
        "tree": "Protection",
        "slot": 20,
        "name": "Improved Shield Slam",
        "icon": "ability_warrior_shieldmastery",
        "ranks": 2,
        "desc": "Snižuje cooldown Shield Slam o [0.75/1.5] sec a po použití dává extra [35/70] % block chance na další útok do 4.5 sec.",
        "requires": "warrior_protection_shield_slam",
        "id": "warrior_protection_improved_shield_slam"
      },
      {
        "tree": "Protection",
        "slot": 21,
        "name": "Reprisal",
        "icon": "ability_warrior_reprisal",
        "ranks": 2,
        "desc": "Zvyšuje damage Revenge o [25/50] % a při úspěšném zásahu má [50/100] % šanci vrátit rage cost.",
        "requires": "warrior_protection_improved_revenge",
        "id": "warrior_protection_reprisal"
      },
      {
        "tree": "Protection",
        "slot": 24,
        "name": "Improved Shield Wall",
        "icon": "ability_warrior_shieldwall",
        "ranks": 2,
        "desc": "Prodlužuje Shield Wall o [1/2] sec a snižuje jeho cooldown o [5/10] min.",
        "requires": null,
        "id": "warrior_protection_improved_shield_wall"
      },
      {
        "tree": "Protection",
        "slot": 25,
        "name": "Defensive Tactics",
        "icon": "ability_warrior_stalwartprotector",
        "ranks": 3,
        "desc": "Při nošení štítu si v ostatních stancích ponecháš [60/120/180] % zvýšeného threat generation z Defensive Stance.",
        "requires": null,
        "id": "warrior_protection_defensive_tactics"
      },
      {
        "tree": "Protection",
        "slot": 26,
        "name": "Concussion Blow",
        "icon": "ability_thunderbolt",
        "ranks": 1,
        "desc": "Způsobí 115 damage, stunuje cíl na 3 sec, generuje vysoký threat, ignoruje 100 % armor cíle a okamžitě vygeneruje 10 rage.",
        "requires": null,
        "id": "warrior_protection_concussion_blow"
      }
    ],
    "warlock": [
      {
        "tree": "Affliction",
        "slot": 0,
        "name": "Suppression",
        "icon": "spell_shadow_unsummonbuilding",
        "ranks": 5,
        "desc": "Snižuje šanci, že nepřátelé odolají tvým Affliction kouzlům, o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warlock_affliction_suppression"
      },
      {
        "tree": "Affliction",
        "slot": 1,
        "name": "Improved Corruption",
        "icon": "spell_shadow_abominationexplosion",
        "ranks": 5,
        "desc": "Snižuje cast time Corruption o [0.3/0.6/0.9/1.2/1.5] sec.",
        "requires": null,
        "id": "warlock_affliction_improved_corruption"
      },
      {
        "tree": "Affliction",
        "slot": 2,
        "name": "Sinister Pursuit",
        "icon": "ability_rogue_envelopingshadows",
        "ranks": 3,
        "desc": "Po útoku démona na cíl ovlivněný Affliction efektem se movement speed démona zvýší o [5/10/15] % na 3 sec.",
        "requires": null,
        "id": "warlock_affliction_sinister_pursuit"
      },
      {
        "tree": "Affliction",
        "slot": 4,
        "name": "Improved Curse of Weakness",
        "icon": "spell_shadow_curseofmannoroth",
        "ranks": 2,
        "desc": "Zvyšuje attack speed reduction z Curse of Weakness o [3/5] %.",
        "requires": null,
        "id": "warlock_affliction_improved_curse_of_weakness"
      },
      {
        "tree": "Affliction",
        "slot": 5,
        "name": "Resilient Shadows",
        "icon": "spell_shadow_soulleech_1",
        "ranks": 3,
        "desc": "Snižuje šanci na dispel tvých Affliction kouzel o dalších [5/10/15] %.",
        "requires": null,
        "id": "warlock_affliction_resilient_shadows"
      },
      {
        "tree": "Affliction",
        "slot": 6,
        "name": "Improved Life Tap",
        "icon": "spell_shadow_burningspirit",
        "ranks": 2,
        "desc": "Zvyšuje množství many získané z Life Tap o [10/20] %.",
        "requires": null,
        "id": "warlock_affliction_improved_life_tap"
      },
      {
        "tree": "Affliction",
        "slot": 7,
        "name": "Improved Drains",
        "icon": "spell_shadow_lifedrain02",
        "ranks": 2,
        "desc": "Zvyšuje účinnost Drain Soul, Drain Life a Drain Mana o [5/10] %.",
        "requires": null,
        "id": "warlock_affliction_improved_drains"
      },
      {
        "tree": "Affliction",
        "slot": 8,
        "name": "Improved Curse of Agony",
        "icon": "spell_shadow_curseofsargeras",
        "ranks": 3,
        "desc": "Zvyšuje damage Curse of Agony o [3/6/10] %.",
        "requires": null,
        "id": "warlock_affliction_improved_curse_of_agony"
      },
      {
        "tree": "Affliction",
        "slot": 9,
        "name": "Fel Concentration",
        "icon": "spell_shadow_fingerofdeath",
        "ranks": 2,
        "desc": "Affliction kouzla mají [35/70] % šanci neztrácet cast time při obdrženém damage.",
        "requires": null,
        "id": "warlock_affliction_fel_concentration"
      },
      {
        "tree": "Affliction",
        "slot": 10,
        "name": "Curse of Exhaustion",
        "icon": "spell_shadow_grimward",
        "ranks": 1,
        "desc": "Sníží movement speed cíle o 10 % na 12 sec. Na jednom cíli může být jen jedna Curse od jednoho warlocka.",
        "requires": null,
        "id": "warlock_affliction_curse_of_exhaustion"
      },
      {
        "tree": "Affliction",
        "slot": 12,
        "name": "Grim Reach",
        "icon": "spell_shadow_callofbone",
        "ranks": 2,
        "desc": "Zvyšuje range Affliction kouzel o [10/20] %.",
        "requires": null,
        "id": "warlock_affliction_grim_reach"
      },
      {
        "tree": "Affliction",
        "slot": 13,
        "name": "Nightfall",
        "icon": "spell_shadow_twilight",
        "ranks": 2,
        "desc": "Corruption, Dark Harvest a Drain kouzla mají po damage [2/4] % šanci vyvolat Shadow Trance: další Shadow Bolt je instantní a garantovaně zasáhne.",
        "requires": null,
        "id": "warlock_affliction_nightfall"
      },
      {
        "tree": "Affliction",
        "slot": 14,
        "name": "Soul Siphon",
        "icon": "spell_shadow_haunting",
        "ranks": 3,
        "desc": "Zvyšuje damage Drain Soul, Dark Harvest a Death Coil o dalších [2/4/6] % za každý tvůj Affliction efekt na cíli, maximálně za 4 efekty.",
        "requires": null,
        "id": "warlock_affliction_soul_siphon"
      },
      {
        "tree": "Affliction",
        "slot": 15,
        "name": "Rapid Deterioration",
        "icon": "spell_shadow_detectinvisibility",
        "ranks": 2,
        "desc": "Zvyšuje casting speed Affliction kouzel o 6 %. Haste efekty navíc zrychlují tick rate DoT a channel Affliction kouzel s [50/100] % účinností a zkracují jejich trvání.",
        "requires": null,
        "id": "warlock_affliction_rapid_deterioration"
      },
      {
        "tree": "Affliction",
        "slot": 17,
        "name": "Siphon Life",
        "icon": "spell_shadow_requiem",
        "ranks": 1,
        "desc": "Přenese 150 Health z cíle na castera během 30 sec.",
        "requires": null,
        "id": "warlock_affliction_siphon_life"
      },
      {
        "tree": "Affliction",
        "slot": 18,
        "name": "Improved Curse of Exhaustion",
        "icon": "spell_shadow_grimward",
        "ranks": 2,
        "desc": "Zvyšuje zpomalení z Curse of Exhaustion o [15/30] %.",
        "requires": "warlock_affliction_curse_of_exhaustion",
        "id": "warlock_affliction_improved_curse_of_exhaustion"
      },
      {
        "tree": "Affliction",
        "slot": 20,
        "name": "Malediction",
        "icon": "spell_shadow_curseofachimonde",
        "ranks": 1,
        "desc": "Curse of Agony může být aktivní společně s tvými ostatními curses kromě Curse of Doom. Curse of Recklessness, Curse of Shadows nebo Curse of Elements zároveň aplikují nejvyšší rank tvé Curse of Agony.",
        "requires": null,
        "id": "warlock_affliction_malediction"
      },
      {
        "tree": "Affliction",
        "slot": 21,
        "name": "Shadow Mastery",
        "icon": "spell_shadow_shadetruesight",
        "ranks": 5,
        "desc": "Zvyšuje damage nebo life drained tvých Shadow kouzel o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warlock_affliction_shadow_mastery"
      },
      {
        "tree": "Affliction",
        "slot": 25,
        "name": "Dark Harvest",
        "icon": "spell_shadow_soulleech",
        "ranks": 1,
        "desc": "Channeluje život cíle: 704 Shadow damage během 8 sec. Během channelu se interval ticků tvých Affliction efektů na cíli zkrátí o 30 %. Pokud cíl při channelu zemře, cooldown Dark Harvest se resetuje.",
        "requires": null,
        "id": "warlock_affliction_dark_harvest"
      },
      {
        "tree": "Demonology",
        "slot": 0,
        "name": "Master Conjuror",
        "icon": "inv_stone_04",
        "ranks": 2,
        "desc": "Zvyšuje healing z Healthstone o [10/20] % a Health/Mana při resurrectu ze Soulstone o [10/20] %.",
        "requires": null,
        "id": "warlock_demonology_master_conjuror"
      },
      {
        "tree": "Demonology",
        "slot": 1,
        "name": "Demonic Embrace",
        "icon": "spell_shadow_metamorphosis",
        "ranks": 5,
        "desc": "Zvyšuje celkovou Stamina o [3/6/9/12/15] %, ale snižuje celkový Spirit o [1/2/3/4/5] %.",
        "requires": null,
        "id": "warlock_demonology_demonic_embrace"
      },
      {
        "tree": "Demonology",
        "slot": 2,
        "name": "Soul Entrapment",
        "icon": "trade_archaeology_highbornesoulmirror",
        "ranks": 3,
        "desc": "Když nemáš pod kontrolou žádného démona, veškerý způsobený damage je zvýšen o [2/4/6] %.",
        "requires": null,
        "id": "warlock_demonology_soul_entrapment"
      },
      {
        "tree": "Demonology",
        "slot": 4,
        "name": "Soul Funnel",
        "icon": "spell_shadow_lifedrain",
        "ranks": 2,
        "desc": "Health Funnel převádí navíc [10/20] % chybějícího Health démona a Mana Funnel navíc [10/20] % chybějící many démona; dodatečný převod tě stojí 30 % této hodnoty.",
        "requires": null,
        "id": "warlock_demonology_soul_funnel"
      },
      {
        "tree": "Demonology",
        "slot": 5,
        "name": "Demonic Aegis",
        "icon": "spell_shadow_ragingscream",
        "ranks": 3,
        "desc": "Zvyšuje účinnost Demon Armor o [20/40/60] %.",
        "requires": null,
        "id": "warlock_demonology_demonic_aegis"
      },
      {
        "tree": "Demonology",
        "slot": 6,
        "name": "Fel Intellect",
        "icon": "spell_holy_magicalsentry",
        "ranks": 3,
        "desc": "Zvyšuje Intellect démona o [10/20/30] % tvého celkového Intellect a umožní [5/10/15] % jeho mana regeneration pokračovat během castění.",
        "requires": null,
        "id": "warlock_demonology_fel_intellect"
      },
      {
        "tree": "Demonology",
        "slot": 9,
        "name": "Fel Domination",
        "icon": "spell_nature_removecurse",
        "ranks": 1,
        "desc": "Další Common demon summoning spell má cast time snížený o 4.5 sec a mana cost o 40 %.",
        "requires": null,
        "id": "warlock_demonology_fel_domination"
      },
      {
        "tree": "Demonology",
        "slot": 10,
        "name": "Fel Stamina",
        "icon": "spell_shadow_antishadow",
        "ranks": 5,
        "desc": "Zvyšuje Stamina démona o [10/20/30/40/50] % tvé celkové Stamina a snižuje šanci, že dostane critical strike, o [1/2/3/4/5] %.",
        "requires": null,
        "id": "warlock_demonology_fel_stamina"
      },
      {
        "tree": "Demonology",
        "slot": 13,
        "name": "Demonic Sacrifice",
        "icon": "spell_shadow_psychicscream",
        "ranks": 1,
        "desc": "Obětuješ démona a získáš efekt: Imp +4 % spell damage, Voidwalker regeneruje 3 % Health každé 4 sec, Succubus -10 % threat, Felhunter regeneruje 3 % Mana každé 4 sec. Efekt skončí při summon/enslave démona.",
        "requires": null,
        "id": "warlock_demonology_demonic_sacrifice"
      },
      {
        "tree": "Demonology",
        "slot": 14,
        "name": "Improved Stones",
        "icon": "inv_jewelry_talisman_fireice",
        "ranks": 2,
        "desc": "Zvyšuje účinnost Felstone, Wrathstone, Voidstone a Spellstone o [25/50] % a crit bonus Firestone o [50/100] %.",
        "requires": null,
        "id": "warlock_demonology_improved_stones"
      },
      {
        "tree": "Demonology",
        "slot": 16,
        "name": "Master Summoner",
        "icon": "spell_shadow_impphaseshift",
        "ranks": 2,
        "desc": "Snižuje cast time summonu Imp, Voidwalker, Succubus a Felhunter o [2/4] sec a jejich mana cost o [30/60] %. Snižuje cooldown Inferno a Demon Gate o [25/50] %.",
        "requires": null,
        "id": "warlock_demonology_master_summoner"
      },
      {
        "tree": "Demonology",
        "slot": 17,
        "name": "Nether Studies",
        "icon": "inv_misc_book_06",
        "ranks": 3,
        "desc": "Zvyšuje efekt Succubus Seduction, Voidwalker Torment, Imp Blood Pact a Felhunter Tainted Blood o [15/30/45] %.",
        "requires": null,
        "id": "warlock_demonology_nether_studies"
      },
      {
        "tree": "Demonology",
        "slot": 18,
        "name": "Unholy Power",
        "icon": "spell_shadow_shadowworddominate",
        "ranks": 3,
        "desc": "Zvyšuje damage tvých démonů o [5/10/15] %.",
        "requires": null,
        "id": "warlock_demonology_unholy_power"
      },
      {
        "tree": "Demonology",
        "slot": 21,
        "name": "Power Overwhelming",
        "icon": "ability_warlock_power_overwhelming",
        "ranks": 1,
        "desc": "Channeluje energii do démona: odstraní z něj crowd control a zvýší jeho damage o 20 % na 10 sec. Démon během efektu ztratí 40 % base health.",
        "requires": null,
        "id": "warlock_demonology_power_overwhelming"
      },
      {
        "tree": "Demonology",
        "slot": 22,
        "name": "Demonic Precision",
        "icon": "spell_shadow_curseoftounges",
        "ranks": 3,
        "desc": "Démoni získají [1/2/3] % melee/spell hit a zdědí [30/60/90] % tvého spell hit a spell crit jako svůj melee/spell hit i crit.",
        "requires": null,
        "id": "warlock_demonology_demonic_precision"
      },
      {
        "tree": "Demonology",
        "slot": 24,
        "name": "Master Demonologist",
        "icon": "spell_shadow_shadowpact",
        "ranks": 5,
        "desc": "Warlock i démon získají efekt podle aktivního démona: Imp snižuje spell cost o [3/6/9/12/15] %, Voidwalker snižuje physical damage taken o [2/4/6/8/10] %, Succubus zvyšuje veškerý damage o [2/4/6/8/10] %, Greater Demons zvyšují spell crit o [2/4/6/8/10] %, ale snižují received healing o [8/16/24/32/40] %.",
        "requires": null,
        "id": "warlock_demonology_master_demonologist"
      },
      {
        "tree": "Demonology",
        "slot": 25,
        "name": "Unleashed Potential",
        "icon": "ability_warlock_demonicpower",
        "ranks": 3,
        "desc": "Critical strike tvých direct damage kouzel umožní démonovi získat [5/10/15] % tvého Fire a Shadow spell bonus damage na 20 sec. Ticky funnel kouzel efekt refreshují. Stackuje až 3×.",
        "requires": null,
        "id": "warlock_demonology_unleashed_potential"
      },
      {
        "tree": "Demonology",
        "slot": 26,
        "name": "Soul Link",
        "icon": "spell_shadow_gathershadows",
        "ranks": 1,
        "desc": "Když ovládáš démona, damage tebe i démona je zvýšen o 5 %. Navíc 25 % damage, který dostaneš, přebírá démon. Greater a Enslaved démoni se už nemohou předčasně utrhnout.",
        "requires": null,
        "id": "warlock_demonology_soul_link"
      },
      {
        "tree": "Destruction",
        "slot": 0,
        "name": "Shadow Vulnerability",
        "icon": "spell_shadow_shadowbolt",
        "ranks": 5,
        "desc": "Shadow Bolt a Drain Soul mají [2/4/6/8/10] % šanci zvýšit Shadow damage na cíli o 20 % na 10 sec; critical hity mají vyšší šanci na proc.",
        "requires": null,
        "id": "warlock_destruction_shadow_vulnerability"
      },
      {
        "tree": "Destruction",
        "slot": 1,
        "name": "Cataclysm",
        "icon": "spell_fire_windsofwoe",
        "ranks": 5,
        "desc": "Snižuje mana cost Destruction kouzel o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warlock_destruction_cataclysm"
      },
      {
        "tree": "Destruction",
        "slot": 2,
        "name": "Demonic Swiftness",
        "icon": "spell_shadow_curseoftounges",
        "ranks": 2,
        "desc": "Snižuje cast time Imp Firebolt o [0.3/0.5] sec a cooldown Succubus Lash of Pain o [3/6] sec.",
        "requires": null,
        "id": "warlock_destruction_demonic_swiftness"
      },
      {
        "tree": "Destruction",
        "slot": 4,
        "name": "Bane",
        "icon": "spell_shadow_deathpact",
        "ranks": 5,
        "desc": "Snižuje cast time Shadow Bolt a Immolate o [0.1/0.2/0.3/0.4/0.5] sec a Soul Fire o [0.4/0.8/1.2/1.6/2] sec.",
        "requires": null,
        "id": "warlock_destruction_bane"
      },
      {
        "tree": "Destruction",
        "slot": 5,
        "name": "Aftermath",
        "icon": "spell_fire_fire",
        "ranks": 3,
        "desc": "Zvyšuje periodic damage Immolate o [2/4/6] % a Destruction kouzla mají [4/7/10] % šanci zpomalit cíl o 50 % na 5 sec.",
        "requires": null,
        "id": "warlock_destruction_aftermath"
      },
      {
        "tree": "Destruction",
        "slot": 6,
        "name": "Intensity",
        "icon": "spell_fire_lavaspawn",
        "ranks": 2,
        "desc": "Fire kouzla mají [35/70] % šanci neztrácet cast time při obdrženém damage.",
        "requires": null,
        "id": "warlock_destruction_intensity"
      },
      {
        "tree": "Destruction",
        "slot": 9,
        "name": "Shadowburn",
        "icon": "spell_shadow_scourgebuild",
        "ranks": 1,
        "desc": "Instant Shadow damage 91–103. Pokud cíl do 5 sec zemře a dává experience nebo honor, caster získá Soul Shard.",
        "requires": null,
        "id": "warlock_destruction_shadowburn"
      },
      {
        "tree": "Destruction",
        "slot": 10,
        "name": "Devastation",
        "icon": "spell_fire_flameshock",
        "ranks": 5,
        "desc": "Zvyšuje critical strike chance Destruction kouzel o [1/2/3/4/5] %.",
        "requires": null,
        "id": "warlock_destruction_devastation"
      },
      {
        "tree": "Destruction",
        "slot": 12,
        "name": "Pyroclasm",
        "icon": "spell_fire_volcano",
        "ranks": 2,
        "desc": "Rain of Fire, Hellfire, Conflagrate a Soul Fire mají [13/26] % šanci stunout cíl na 3 sec.",
        "requires": null,
        "id": "warlock_destruction_pyroclasm"
      },
      {
        "tree": "Destruction",
        "slot": 13,
        "name": "Destructive Reach",
        "icon": "spell_shadow_corpseexplode",
        "ranks": 2,
        "desc": "Zvyšuje range Destruction kouzel o [10/20] % a radius Hellfire o [10/20] %.",
        "requires": null,
        "id": "warlock_destruction_destructive_reach"
      },
      {
        "tree": "Destruction",
        "slot": 14,
        "name": "Improved Searing Pain",
        "icon": "spell_fire_soulburn",
        "ranks": 5,
        "desc": "Zvyšuje critical strike chance Searing Pain o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warlock_destruction_improved_searing_pain"
      },
      {
        "tree": "Destruction",
        "slot": 17,
        "name": "Improved Soul Fire",
        "icon": "spell_fire_fireball02",
        "ranks": 2,
        "desc": "Soul Fire má [50/100] % šanci vrátit Soul Shard a zvýšit Fire damage o 10 % na 30 sec.",
        "requires": null,
        "id": "warlock_destruction_improved_soul_fire"
      },
      {
        "tree": "Destruction",
        "slot": 18,
        "name": "Improved Immolate",
        "icon": "spell_fire_immolation",
        "ranks": 5,
        "desc": "Zvyšuje damage Immolate o [4/8/12/16/20] %.",
        "requires": null,
        "id": "warlock_destruction_improved_immolate"
      },
      {
        "tree": "Destruction",
        "slot": 21,
        "name": "Ruin",
        "icon": "spell_shadow_shadowwordpain",
        "ranks": 1,
        "desc": "Zvyšuje bonus critical strike damage Destruction kouzel o 100 %.",
        "requires": "warlock_destruction_devastation",
        "id": "warlock_destruction_ruin"
      },
      {
        "tree": "Destruction",
        "slot": 22,
        "name": "Emberstorm",
        "icon": "spell_fire_selfdestruct",
        "ranks": 5,
        "desc": "Zvyšuje damage Fire kouzel o [2/4/6/8/10] %.",
        "requires": null,
        "id": "warlock_destruction_emberstorm"
      },
      {
        "tree": "Destruction",
        "slot": 25,
        "name": "Conflagrate",
        "icon": "spell_fire_fireball",
        "ranks": 1,
        "desc": "Zapálí cíl, způsobí 249–315 Fire damage a spotřebuje 3 sec tvého Immolate pro dodatečný damage odpovídající této části.",
        "requires": null,
        "id": "warlock_destruction_conflagrate"
      }
    ],
    "priest": [
      {
        "tree": "Discipline",
        "slot": 0,
        "name": "Wand Specialization",
        "icon": "inv_wand_01",
        "ranks": 2,
        "desc": "Zvyšuje damage a hit chance s Wands a Bows o [13/25] % a [5/10] %. Úspěšné útoky mají šanci obnovit manu.",
        "requires": null,
        "id": "priest_discipline_wand_specialization"
      },
      {
        "tree": "Discipline",
        "slot": 1,
        "name": "Piercing Light",
        "icon": "spell_holy_retribution",
        "ranks": 3,
        "desc": "Snižuje šanci nepřátel odolat tvým Holy a Discipline kouzlům o [2/4/6] %.",
        "requires": null,
        "id": "priest_discipline_piercing_light"
      },
      {
        "tree": "Discipline",
        "slot": 2,
        "name": "Mental Agility",
        "icon": "ability_hibernation",
        "ranks": 5,
        "desc": "Snižuje mana cost instant kouzel a offensive Holy/Discipline kouzel o [2/4/6/8/10] %.",
        "requires": null,
        "id": "priest_discipline_mental_agility"
      },
      {
        "tree": "Discipline",
        "slot": 4,
        "name": "Silent Resolve",
        "icon": "spell_nature_manaregentotem",
        "ranks": 5,
        "desc": "Snižuje threat generovaný tvými kouzly o [4/8/12/16/20] %.",
        "requires": null,
        "id": "priest_discipline_silent_resolve"
      },
      {
        "tree": "Discipline",
        "slot": 5,
        "name": "Unbreakable Will",
        "icon": "spell_magic_magearmor",
        "ranks": 5,
        "desc": "Zvyšuje šanci odolat Stun, Fear a Silence efektům o [3/6/9/12/15] %.",
        "requires": null,
        "id": "priest_discipline_unbreakable_will"
      },
      {
        "tree": "Discipline",
        "slot": 6,
        "name": "Blessed Concentration",
        "icon": "spell_holy_restoration",
        "ranks": 2,
        "desc": "Po melee/ranged critical hitu máš [50/100] % šanci získat Focused Casting na 6 sec: neztrácíš cast time při damage a interrupt resistance +[10/20] %.",
        "requires": null,
        "id": "priest_discipline_blessed_concentration"
      },
      {
        "tree": "Discipline",
        "slot": 8,
        "name": "Improved Power Word: Fortitude",
        "icon": "spell_holy_wordfortitude",
        "ranks": 2,
        "desc": "Zvyšuje efekt Power Word: Fortitude a Prayer of Fortitude o [15/30] %.",
        "requires": null,
        "id": "priest_discipline_improved_power_word__fortitude"
      },
      {
        "tree": "Discipline",
        "slot": 9,
        "name": "Improved Inner Fire",
        "icon": "spell_holy_innerfire",
        "ranks": 2,
        "desc": "Zvyšuje efekty Inner Fire o [15/30] %.",
        "requires": null,
        "id": "priest_discipline_improved_inner_fire"
      },
      {
        "tree": "Discipline",
        "slot": 10,
        "name": "Inner Focus",
        "icon": "spell_frost_windwalkon",
        "ranks": 1,
        "desc": "Aktivace sníží mana cost dalšího kouzla o 100 % a pokud může critnout, zvýší jeho crit chance o 25 %.",
        "requires": null,
        "id": "priest_discipline_inner_focus"
      },
      {
        "tree": "Discipline",
        "slot": 12,
        "name": "Improved Power Word: Shield",
        "icon": "spell_holy_powerwordshield",
        "ranks": 3,
        "desc": "Zvyšuje damage absorbovaný Power Word: Shield o [5/10/15] %.",
        "requires": null,
        "id": "priest_discipline_improved_power_word__shield"
      },
      {
        "tree": "Discipline",
        "slot": 13,
        "name": "Meditation",
        "icon": "spell_nature_sleep",
        "ranks": 3,
        "desc": "Umožní [5/10/15] % mana regeneration pokračovat během castění.",
        "requires": null,
        "id": "priest_discipline_meditation"
      },
      {
        "tree": "Discipline",
        "slot": 14,
        "name": "Searing Light",
        "icon": "spell_holy_searinglightpriest",
        "ranks": 3,
        "desc": "Critical strike tvých damaging Holy/Discipline kouzel má [33/66/100] % šanci způsobit, že další Smite je instantní a stojí o 50 % méně many. Trvá 10 sec.",
        "requires": null,
        "id": "priest_discipline_searing_light"
      },
      {
        "tree": "Discipline",
        "slot": 16,
        "name": "Purifying Flames",
        "icon": "spell_holy_searinglight",
        "ranks": 2,
        "desc": "Holy Fire má [50/100] % šanci zvýšit tvůj Holy damage o 12 % na 10 sec.",
        "requires": null,
        "id": "priest_discipline_purifying_flames"
      },
      {
        "tree": "Discipline",
        "slot": 17,
        "name": "Mental Strength",
        "icon": "spell_nature_enchantarmor",
        "ranks": 3,
        "desc": "Zvyšuje celkový Intellect o [3/6/10] % a spell casting speed o [1/2/3] %.",
        "requires": null,
        "id": "priest_discipline_mental_strength"
      },
      {
        "tree": "Discipline",
        "slot": 18,
        "name": "Enlighten",
        "icon": "btnholyscriptures",
        "ranks": 1,
        "desc": "Označí party membera na 30 min. Při castu Discipline/Holy kouzla máš šanci způsobit Holy damage za 4 % jeho total health a zvýšit tobě i jemu spell damage/healing o 10 % na 8 sec; na sobě je bonus 15 %. Jen jeden cíl může být pod tuteláží.",
        "requires": null,
        "id": "priest_discipline_enlighten"
      },
      {
        "tree": "Discipline",
        "slot": 20,
        "name": "Resurgent Shield",
        "icon": "spell_holy_blessingofprotection",
        "ranks": 1,
        "desc": "Když se Power Word: Shield rozbije, vrátí 25 % jeho base mana cost a zvýší Holy damage/healing až o 10 % celkové absorb hodnoty štítu na 8 sec.",
        "requires": "priest_discipline_improved_power_word__shield",
        "id": "priest_discipline_resurgent_shield"
      },
      {
        "tree": "Discipline",
        "slot": 21,
        "name": "Force of Will",
        "icon": "spell_nature_slowingtotem",
        "ranks": 5,
        "desc": "Zvyšuje spell damage a critical strike chance offensive kouzel o [1/2/3/4/5] % a absorb Power Word: Shield o [4/8/12/16/20] %.",
        "requires": null,
        "id": "priest_discipline_force_of_will"
      },
      {
        "tree": "Discipline",
        "slot": 25,
        "name": "Chastise",
        "icon": "spell_holy_unyieldingfaith",
        "ranks": 1,
        "desc": "Způsobí 139–160 Holy damage. Nepřátelský cíl dezorientuje až na 2 sec nebo do obdrženého damage. Spojenci zvýší attack/casting speed o 13 % na 8 sec, při critu na 12 sec; nelze použít na spojence pod 80 % HP nebo pod lvl 35.",
        "requires": null,
        "id": "priest_discipline_chastise"
      },
      {
        "tree": "Holy",
        "slot": 0,
        "name": "Improved Renew",
        "icon": "spell_holy_renew",
        "ranks": 3,
        "desc": "Zvyšuje healing z Renew o [5/10/15] %.",
        "requires": null,
        "id": "priest_holy_improved_renew"
      },
      {
        "tree": "Holy",
        "slot": 1,
        "name": "Holy Focus",
        "icon": "spell_holy_healingfocus",
        "ranks": 2,
        "desc": "Holy kouzla mají [35/70] % šanci neztrácet cast time při obdrženém damage.",
        "requires": null,
        "id": "priest_holy_holy_focus"
      },
      {
        "tree": "Holy",
        "slot": 2,
        "name": "Divinity",
        "icon": "spell_holy_sealofsalvation",
        "ranks": 5,
        "desc": "Zvyšuje critical effect chance Holy a Discipline kouzel o [1/2/3/4/5] %.",
        "requires": null,
        "id": "priest_holy_divinity"
      },
      {
        "tree": "Holy",
        "slot": 4,
        "name": "Divine Fury",
        "icon": "spell_holy_sealofwrath",
        "ranks": 5,
        "desc": "Snižuje cast time Smite, Holy Fire, Heal a Greater Heal o [0.1/0.2/0.3/0.4/0.5] sec.",
        "requires": null,
        "id": "priest_holy_divine_fury"
      },
      {
        "tree": "Holy",
        "slot": 5,
        "name": "Spell Warding",
        "icon": "spell_holy_spellwarding",
        "ranks": 3,
        "desc": "Snižuje veškerý spell damage taken o [3/6/10] %.",
        "requires": null,
        "id": "priest_holy_spell_warding"
      },
      {
        "tree": "Holy",
        "slot": 6,
        "name": "Holy Reach",
        "icon": "spell_holy_purify",
        "ranks": 2,
        "desc": "Zvyšuje range Smite, Holy Fire a Chastise a radius Prayer of Healing a Holy Nova o [10/20] %.",
        "requires": null,
        "id": "priest_holy_holy_reach"
      },
      {
        "tree": "Holy",
        "slot": 8,
        "name": "Blessed Recovery",
        "icon": "spell_holy_blessedrecovery",
        "ranks": 3,
        "desc": "Po melee/ranged critical hitu se během 6 sec vyléčíš za [8/16/25] % obdrženého damage.",
        "requires": null,
        "id": "priest_holy_blessed_recovery"
      },
      {
        "tree": "Holy",
        "slot": 9,
        "name": "Inspiration",
        "icon": "spell_holy_layonhands",
        "ranks": 3,
        "desc": "Po critical effectu z Flash Heal, Heal, Greater Heal nebo Prayer of Healing zvýší armor cíle o [8/16/25] % na 15 sec.",
        "requires": null,
        "id": "priest_holy_inspiration"
      },
      {
        "tree": "Holy",
        "slot": 10,
        "name": "Holy Nova",
        "icon": "spell_holy_holynova",
        "ranks": 1,
        "desc": "Explosion kolem castera: 27–31 Holy damage nepřátelům do 10 yd a 54–62 healing party členům do 10 yd. Ve Shadowform ti místo healování škodí. Efekty generují snížený threat.",
        "requires": null,
        "id": "priest_holy_holy_nova"
      },
      {
        "tree": "Holy",
        "slot": 12,
        "name": "Swift Recovery",
        "icon": "spell_holy_resurrection",
        "ranks": 2,
        "desc": "Healing tvých heal kouzel je zvýšen o [3/6] %, pokud má cíl Renew.",
        "requires": null,
        "id": "priest_holy_swift_recovery"
      },
      {
        "tree": "Holy",
        "slot": 13,
        "name": "Improved Healing",
        "icon": "spell_holy_heal02",
        "ranks": 3,
        "desc": "Snižuje mana cost Lesser Heal, Heal, Greater Heal a Prayer of Healing o [5/10/15] %.",
        "requires": null,
        "id": "priest_holy_improved_healing"
      },
      {
        "tree": "Holy",
        "slot": 14,
        "name": "Spiritual Guidance",
        "icon": "spell_holy_spiritualguidence",
        "ranks": 5,
        "desc": "Zvyšuje spell damage a healing až o [5/10/15/20/25] % tvého celkového Spirit.",
        "requires": null,
        "id": "priest_holy_spiritual_guidance"
      },
      {
        "tree": "Holy",
        "slot": 17,
        "name": "Spirit of Redemption",
        "icon": "inv_enchant_essenceeternallarge",
        "ranks": 1,
        "desc": "Zvyšuje total Spirit o 5 %. Po smrti se na 10 sec staneš Spirit of Redemption: nelze se hýbat ani být cílen, ale můžeš zdarma castit healing kouzla. Po skončení zemřeš.",
        "requires": null,
        "id": "priest_holy_spirit_of_redemption"
      },
      {
        "tree": "Holy",
        "slot": 18,
        "name": "Reservoir of Light",
        "icon": "spell_holy_summonlightwell",
        "ranks": 3,
        "desc": "Zvyšuje počet charges Lightwell o [1/3/5].",
        "requires": null,
        "id": "priest_holy_reservoir_of_light"
      },
      {
        "tree": "Holy",
        "slot": 21,
        "name": "Spiritual Healing",
        "icon": "spell_nature_moonglow",
        "ranks": 5,
        "desc": "Zvyšuje healing tvých healing kouzel o [6/12/18/24/30] %.",
        "requires": null,
        "id": "priest_holy_spiritual_healing"
      },
      {
        "tree": "Holy",
        "slot": 25,
        "name": "Proclaim Champion",
        "icon": "spell_holy_proclaimchampion_02",
        "ranks": 1,
        "desc": "Označí friendly target jako Champion na 2 hodiny: snižuje damage taken o 5 %, umožní Champion kouzla a ty získáváš manu rovnou 2 % damage, který Champion obdrží. Jen jeden Champion najednou.",
        "requires": null,
        "id": "priest_holy_proclaim_champion"
      },
      {
        "tree": "Shadow",
        "slot": 0,
        "name": "Spirit Tap",
        "icon": "spell_shadow_requiem",
        "ranks": 5,
        "desc": "Po zabití cíle dávajícího experience máš [20/40/60/80/100] % šanci získat 100 % bonus ke Spirit na 15 sec. Během efektu regeneruješ 50 % many i při castění.",
        "requires": null,
        "id": "priest_shadow_spirit_tap"
      },
      {
        "tree": "Shadow",
        "slot": 1,
        "name": "Blackout",
        "icon": "spell_shadow_gathershadows",
        "ranks": 5,
        "desc": "Shadow damage kouzla mají [2/4/6/8/10] % šanci stunout cíl na 2 sec.",
        "requires": null,
        "id": "priest_shadow_blackout"
      },
      {
        "tree": "Shadow",
        "slot": 2,
        "name": "Shadow Affinity",
        "icon": "spell_shadow_shadowward",
        "ranks": 3,
        "desc": "Snižuje threat z tvých Shadow kouzel o [8/16/25] %.",
        "requires": null,
        "id": "priest_shadow_shadow_affinity"
      },
      {
        "tree": "Shadow",
        "slot": 4,
        "name": "Improved Shadow Word: Pain",
        "icon": "spell_shadow_shadowwordpain",
        "ranks": 2,
        "desc": "Zvyšuje trvání Shadow Word: Pain o [3/6] sec.",
        "requires": null,
        "id": "priest_shadow_improved_shadow_word__pain"
      },
      {
        "tree": "Shadow",
        "slot": 5,
        "name": "Shadow Focus",
        "icon": "spell_shadow_burningspirit",
        "ranks": 5,
        "desc": "Snižuje šanci cíle odolat tvým Shadow kouzlům o [2/4/6/8/10] %.",
        "requires": null,
        "id": "priest_shadow_shadow_focus"
      },
      {
        "tree": "Shadow",
        "slot": 6,
        "name": "Improved Psychic Scream",
        "icon": "spell_shadow_psychicscream",
        "ranks": 2,
        "desc": "Snižuje cooldown Psychic Scream o [2/4] sec.",
        "requires": null,
        "id": "priest_shadow_improved_psychic_scream"
      },
      {
        "tree": "Shadow",
        "slot": 8,
        "name": "Improved Mind Blast",
        "icon": "spell_shadow_unholyfrenzy",
        "ranks": 5,
        "desc": "Snižuje cooldown Mind Blast o [0.5/1/1.5/2/2.5] sec.",
        "requires": null,
        "id": "priest_shadow_improved_mind_blast"
      },
      {
        "tree": "Shadow",
        "slot": 9,
        "name": "Mind Flay",
        "icon": "spell_shadow_siphonmana",
        "ranks": 1,
        "desc": "Channel na 3 sec způsobí 75 Shadow damage a zpomalí movement speed cíle o 50 %.",
        "requires": null,
        "id": "priest_shadow_mind_flay"
      },
      {
        "tree": "Shadow",
        "slot": 10,
        "name": "Improved Mana Burn",
        "icon": "spell_shadow_manaburn",
        "ranks": 2,
        "desc": "Snižuje cast time Mana Burn. Zdrojová kalkulačka má u tohoto tooltipu useknutou hodnotu.",
        "requires": null,
        "id": "priest_shadow_improved_mana_burn"
      },
      {
        "tree": "Shadow",
        "slot": 12,
        "name": "Improved Fade",
        "icon": "spell_magic_lesserinvisibilty",
        "ranks": 2,
        "desc": "Snižuje cooldown Fade o [3/6] sec.",
        "requires": null,
        "id": "priest_shadow_improved_fade"
      },
      {
        "tree": "Shadow",
        "slot": 13,
        "name": "Shadow Reach",
        "icon": "spell_shadow_chilltouch",
        "ranks": 3,
        "desc": "Zvyšuje range Shadow damage kouzel o [6/13/20] %.",
        "requires": null,
        "id": "priest_shadow_shadow_reach"
      },
      {
        "tree": "Shadow",
        "slot": 14,
        "name": "Shadow Weaving",
        "icon": "spell_shadow_blackplague",
        "ranks": 5,
        "desc": "Shadow damage kouzla mají [20/40/60/80/100] % šanci zvýšit Shadow damage received cíle o 3 % na 15 sec. Stackuje až 5×.",
        "requires": null,
        "id": "priest_shadow_shadow_weaving"
      },
      {
        "tree": "Shadow",
        "slot": 17,
        "name": "Silence",
        "icon": "spell_shadow_impphaseshift",
        "ranks": 1,
        "desc": "Umlčí cíl na 5 sec.",
        "requires": null,
        "id": "priest_shadow_silence"
      },
      {
        "tree": "Shadow",
        "slot": 18,
        "name": "Vampiric Embrace",
        "icon": "spell_shadow_unsummonbuilding",
        "ranks": 1,
        "desc": "Afflictne cíl Shadow energií: party členové se léčí za 20 % Shadow spell damage, který způsobíš, po dobu 1 min.",
        "requires": null,
        "id": "priest_shadow_vampiric_embrace"
      },
      {
        "tree": "Shadow",
        "slot": 19,
        "name": "Vampiric Touch",
        "icon": "spell_shadow_improvedvampiricembrace",
        "ranks": 2,
        "desc": "Zvyšuje procento healingu z Vampiric Embrace o dalších [2/5] % a způsobí, že party členové získávají manu rovnou [1/2] % tvého Shadow spell damage.",
        "requires": null,
        "id": "priest_shadow_vampiric_touch"
      },
      {
        "tree": "Shadow",
        "slot": 21,
        "name": "Darkness",
        "icon": "spell_shadow_twilight",
        "ranks": 5,
        "desc": "Zvyšuje Shadow spell damage o [2/4/6/8/10] %.",
        "requires": null,
        "id": "priest_shadow_darkness"
      },
      {
        "tree": "Shadow",
        "slot": 25,
        "name": "Shadowform",
        "icon": "spell_shadow_shadowform",
        "ranks": 1,
        "desc": "Shadowform zvyšuje Shadow damage o 15 % a snižuje Physical damage taken o 15 %. Nelze castit Holy kouzla kromě Holy Nova.",
        "requires": null,
        "id": "priest_shadow_shadowform"
      }
    ]
  },
  "paths": {
    "warrior": [
      "warrior_protection_improved_bloodrage",
      "warrior_protection_improved_bloodrage",
      "warrior_protection_shield_specialization",
      "warrior_protection_shield_specialization",
      "warrior_protection_shield_specialization",
      "warrior_protection_shield_specialization",
      "warrior_protection_shield_specialization",
      "warrior_protection_anticipation",
      "warrior_protection_anticipation",
      "warrior_protection_anticipation",
      "warrior_protection_toughness",
      "warrior_protection_toughness",
      "warrior_protection_toughness",
      "warrior_protection_toughness",
      "warrior_protection_toughness",
      "warrior_protection_last_stand",
      "warrior_protection_improved_revenge",
      "warrior_protection_improved_revenge",
      "warrior_protection_improved_revenge",
      "warrior_protection_improved_taunt",
      "warrior_protection_defiance",
      "warrior_protection_defiance",
      "warrior_protection_defiance",
      "warrior_protection_defiance",
      "warrior_protection_defiance",
      "warrior_protection_one_handed_weapon_specialization",
      "warrior_protection_one_handed_weapon_specialization",
      "warrior_protection_one_handed_weapon_specialization",
      "warrior_protection_one_handed_weapon_specialization",
      "warrior_protection_one_handed_weapon_specialization",
      "warrior_protection_shield_slam",
      "warrior_protection_improved_shield_slam",
      "warrior_protection_improved_shield_slam",
      "warrior_protection_reprisal",
      "warrior_protection_reprisal",
      "warrior_protection_concussion_blow",
      "warrior_protection_gag_order",
      "warrior_protection_gag_order",
      "warrior_protection_defensive_tactics",
      "warrior_protection_defensive_tactics",
      "warrior_protection_defensive_tactics",
      "warrior_fury_cruelty",
      "warrior_fury_cruelty",
      "warrior_fury_cruelty",
      "warrior_fury_cruelty",
      "warrior_fury_cruelty",
      "warrior_arms_tactical_mastery",
      "warrior_arms_tactical_mastery",
      "warrior_arms_tactical_mastery",
      "warrior_arms_tactical_mastery",
      "warrior_arms_tactical_mastery"
    ],
    "warlock": [
      "warlock_affliction_improved_corruption",
      "warlock_affliction_improved_corruption",
      "warlock_affliction_improved_corruption",
      "warlock_affliction_improved_corruption",
      "warlock_affliction_improved_corruption",
      "warlock_affliction_improved_life_tap",
      "warlock_affliction_improved_life_tap",
      "warlock_affliction_improved_drains",
      "warlock_affliction_improved_drains",
      "warlock_affliction_resilient_shadows",
      "warlock_affliction_improved_curse_of_agony",
      "warlock_affliction_improved_curse_of_agony",
      "warlock_affliction_improved_curse_of_agony",
      "warlock_affliction_fel_concentration",
      "warlock_affliction_fel_concentration",
      "warlock_affliction_curse_of_exhaustion",
      "warlock_affliction_grim_reach",
      "warlock_affliction_grim_reach",
      "warlock_affliction_nightfall",
      "warlock_affliction_nightfall",
      "warlock_affliction_soul_siphon",
      "warlock_affliction_soul_siphon",
      "warlock_affliction_soul_siphon",
      "warlock_affliction_rapid_deterioration",
      "warlock_affliction_rapid_deterioration",
      "warlock_affliction_siphon_life",
      "warlock_affliction_malediction",
      "warlock_affliction_shadow_mastery",
      "warlock_affliction_shadow_mastery",
      "warlock_affliction_shadow_mastery",
      "warlock_affliction_shadow_mastery",
      "warlock_affliction_shadow_mastery",
      "warlock_affliction_dark_harvest",
      "warlock_destruction_shadow_vulnerability",
      "warlock_destruction_shadow_vulnerability",
      "warlock_destruction_shadow_vulnerability",
      "warlock_destruction_shadow_vulnerability",
      "warlock_destruction_shadow_vulnerability",
      "warlock_destruction_bane",
      "warlock_destruction_bane",
      "warlock_destruction_bane",
      "warlock_destruction_bane",
      "warlock_destruction_bane",
      "warlock_destruction_devastation",
      "warlock_destruction_devastation",
      "warlock_destruction_devastation",
      "warlock_destruction_devastation",
      "warlock_destruction_devastation",
      "warlock_destruction_shadowburn",
      "warlock_destruction_destructive_reach",
      "warlock_destruction_destructive_reach"
    ],
    "priest": [
      "priest_discipline_mental_agility",
      "priest_discipline_mental_agility",
      "priest_discipline_mental_agility",
      "priest_discipline_mental_agility",
      "priest_discipline_mental_agility",
      "priest_discipline_silent_resolve",
      "priest_discipline_silent_resolve",
      "priest_discipline_silent_resolve",
      "priest_discipline_silent_resolve",
      "priest_discipline_silent_resolve",
      "priest_discipline_improved_power_word__fortitude",
      "priest_discipline_improved_power_word__fortitude",
      "priest_discipline_improved_inner_fire",
      "priest_discipline_improved_inner_fire",
      "priest_discipline_inner_focus",
      "priest_discipline_improved_power_word__shield",
      "priest_discipline_improved_power_word__shield",
      "priest_discipline_improved_power_word__shield",
      "priest_discipline_meditation",
      "priest_discipline_meditation",
      "priest_discipline_meditation",
      "priest_discipline_mental_strength",
      "priest_discipline_mental_strength",
      "priest_discipline_mental_strength",
      "priest_discipline_searing_light",
      "priest_discipline_resurgent_shield",
      "priest_discipline_force_of_will",
      "priest_discipline_force_of_will",
      "priest_discipline_force_of_will",
      "priest_discipline_force_of_will",
      "priest_discipline_force_of_will",
      "priest_discipline_enlighten",
      "priest_discipline_chastise",
      "priest_holy_improved_renew",
      "priest_holy_improved_renew",
      "priest_holy_improved_renew",
      "priest_holy_holy_focus",
      "priest_holy_holy_focus",
      "priest_holy_divinity",
      "priest_holy_divinity",
      "priest_holy_divinity",
      "priest_holy_divinity",
      "priest_holy_divinity",
      "priest_holy_divine_fury",
      "priest_holy_divine_fury",
      "priest_holy_divine_fury",
      "priest_holy_divine_fury",
      "priest_holy_divine_fury",
      "priest_holy_inspiration",
      "priest_holy_inspiration",
      "priest_holy_inspiration"
    ]
  }
};
